scripts:

  borrow-service-run:
    timeout: 30 Minutes
    start_when:
      uberjar has been built:
        script_key: borrow-build-uberjar
      database has been created:
        script_key: create-database
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_BORROW_DIR
      export DB_NAME=${LEIHS_DATABASE_NAME}
      export HTTP_PORT=${LEIHS_BORROW_HTTP_PORT}
      unset PGPORT
      unset PGUSER
      mkdir tmp
      PGPORT="${PG10PORT}" PGUSER="${PG10USER}" \
        ./bin/run --pid-file tmp/service.pid

  borrow-service-is-running:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      until curl --silent --fail -I \
        -H 'Accept: application/json' \
        ${LEIHS_BORROW_HTTP_BASE_URL}/borrow/status;
        do sleep 1;
      done
    start_when:
      run server is executing:
        script_key: borrow-service-run
        states: [executing]

  test:
    start_when:
      borrow service is running:
        script_key: borrow-service-is-running

  borrow-service-stop:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_BORROW_DIR
      export PID=$(cat tmp/service.pid)
      kill $PID
      tail --pid=$PID -f /dev/null
    start_when:
      test is terminal:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]

  delete-database:
    start_when:
       borrow-service-stop is in terminal state:
        script_key: borrow-service-stop
        states: [aborted, defective, passed, failed, skipped]
