name: LEIHS/leihs/borrow
windows:
  2:
    name: dev-run-backend
    command: |
      ./bin/dev-run-backend
  3:
    name: dev-run-frontend
    command: |
      ./bin/dev-run-frontend
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  7:
    name: test
    command: |
      export RAILS_ENV=test
  8:
    name: shared-clj
    command: |
      cd shared-clj
