jobs:
  build-borrow-uberjar:
    name: Build prod ready uberjar
    run_when: &ON_BRANCH_UPDATE
      any branch has been updated:
        type: branch
        include_match: ^.*$
    include: cider-ci/uberjar_job-component.yml

  feature-specs:
    name: Feature specs
    depends_on: &SPEC_DEPS
      uberjar was built:
        type: job
        job_key: build-borrow-uberjar
        states: [passed]
    run_when: *SPEC_DEPS
    context: { include: cider-ci/feature-specs_job-context.yml }

  backend-specs:
    name: 'Backend: Run specs'
    depends_on: *SPEC_DEPS
    run_when: *SPEC_DEPS
    context: { include: cider-ci/backend-specs_job-context.yml }

  lint:
    name: Lint
    depends_on: *SPEC_DEPS
    run_when: *SPEC_DEPS
    context: { include: cider-ci/lint_job-context.yml }

  meta:
    name: Meta
    description: |
      Various superordinate quality assurance tasks
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    include: cider-ci/meta_job-component.yml

  all-ok:
    name: 'All Tests OK'
    depends_on: &ALLOK_DEPS
      meta was successful:
        type: job
        job_key: meta
        states: [passed]
      backend-specs was successful:
        type: job
        job_key: backend-specs
        states: [passed]
      lint was successful:
        type: job
        job_key: lint
        states: [passed]
      feature-specs was successful:
        type: job
        job_key: feature-specs
        states: [passed]
      build-borrow-uberjar was successful:
        type: job
        job_key: build-borrow-uberjar
        states: [passed]
      good to merge of the database:
        job_key: good-to-merge
        type: job
        submodule: ['database']
        states: [passed]
    run_when: *ALLOK_DEPS
    task: 'echo ALL OK'

  good-to-merge:
    name: '⚑ Good To Merge'
    priority: 99 # no tasks here anyways
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!
    depends_on: &GOOD_TO_MERGE_DEPENDENCIES
      all passed: { type: job, job_key: all-ok, states: [passed] }
    run_when: *GOOD_TO_MERGE_DEPENDENCIES
    context: { include: cider-ci/good-to-merge_job-context.yml }
