source 'https://rubygems.org'
eval_gemfile 'database/Gemfile'

# gem 'geckodriver-helper', '0.21.0'
gem 'capybara', '3.36.0'
gem 'selenium-webdriver', '4.1.0'
gem 'edn'
gem 'faraday'
gem 'graphlient'
gem 'sinatra'
gem 'turnip', github: 'leihs/turnip', branch: 'ambiguous-steps'
