source 'https://rubygems.org'
eval_gemfile 'database/Gemfile'

gem 'geckodriver-helper', '0.21.0'
gem 'capybara', '~> 3.8'
gem 'edn'
gem 'faraday'
gem 'graphlient'
gem 'selenium-webdriver', '~> 3.14'
gem 'sinatra'
gem 'turnip', github: 'leihs/turnip', branch: 'ambiguous-steps'
