query myRentals(
  $userId: UUID
  $searchTerm: NonEmptyText
  $refinedRentalState: RefinedRentalStateEnum
  $poolIds: [UUID!]
  $from: Date
  $until: Date
) {
  openRentals: rentals(
    userId: $userId
    rentalState: OPEN
    refinedRentalState: $refinedRentalState
    searchTerm: $searchTerm
    poolIds: $poolIds
    from: $from
    until: $until
    orderBy: [{ attribute: CREATED_AT, direction: DESC }]
  ) {
    ...rentalConProps
  }
  closedRentals: rentals(
    userId: $userId
    rentalState: CLOSED
    refinedRentalState: $refinedRentalState
    searchTerm: $searchTerm
    poolIds: $poolIds
    from: $from
    until: $until
    orderBy: [{ attribute: CREATED_AT, direction: DESC }]
  ) {
    ...rentalConProps
  }
}

fragment rentalConProps on RentalsConnection {
  edges {
    node {
      ...rentalProps
    }
  }
}

fragment rentalProps on Rental {
  id

  isCustomerOrder
  state: rentalState
  fulfillmentStates: refinedRentalState

  title
  purpose

  fromDate
  untilDate

  totalDays
  totalQuantity

  approveFulfillment {
    fulfilledQuantity
    toFulfillQuantity
  }

  rejectedQuantity
  expiredUnapprovedQuantity

  pickupFulfillment {
    fulfilledQuantity
    toFulfillQuantity
  }
  expiredQuantity

  returnFulfillment {
    fulfilledQuantity
    toFulfillQuantity
  }

  overdueQuantity

  createdAt
  updatedAt

}
