query customerOrderShow($id: UUID!, $userId: UUID) {
  order(id: $id, userId: $userId) {
    id
    purpose
    title
    state
    createdAt
    updatedAt
    subOrdersByPool {
      id
      state
      rejectedReason
      inventoryPool {
        id
        name
        isActive
      }
      # createdAt
      # updatedAt
      reservations {
        id
        status
        startDate
        endDate
        model {
          id
          name
        }
      }
    }
    reservations {
      id
      status
      startDate
      endDate
      model {
        id
        name
      }
    }
    contracts {
      edges {
        node {
          id
          note
          reservations {
            id
            status
            startDate
            endDate
            model {
              id
              name
            }
          }
        }
      }
    }
    pickups {
      date
      reservations {
        id
        status
        startDate
        endDate
        model {
          id
          name
        }
      }
    }
    returns {
      date
      reservations {
        id
        status
        startDate
        endDate
        model {
          id
          name
        }
      }
    }
  }
}
