query customerOrderShow($id: UUID!, $userId: UUID) {
  order(id: $id, userId: $userId) {
    id
    purpose
    title
    state
    createdAt
    updatedAt
    subOrdersByPool {
      id
      state
      rejectedReason
      inventoryPool {
        id
        name
      }
      # createdAt
      # updatedAt
      reservations {
        id
        # status
        startDate
        endDate
        model {
          id
          name
        }
      }
    }
  }
}
