query customerOrdersIndex($userId: UUID) {
  submittedOrders: rentals(userId: $userId states: [SUBMITTED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
  rejectedOrders: rentals(userId: $userId states: [REJECTED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
  approvedOrders: rentals(userId: $userId states: [APPROVED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
}

fragment OrderConProps on RentalsConnection {
  edges {
    node {
      ...orderProps
    }
  }
}

fragment orderProps on Rental {
  id
  state
  rentalState
  refinedRentalState
  purpose
  createdAt
  updatedAt
  subOrdersByPool {
    id
  }
}
