query customerOrdersIndex($userId: UUID) {
  submittedOrders: orders(userId: $userId states: [SUBMITTED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
  rejectedOrders: orders(userId: $userId states: [REJECTED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
  approvedOrders: orders(userId: $userId states: [APPROVED] orderBy: [{ attribute: CREATED_AT, direction: DESC }]) {
    ...OrderConProps
  }
}

fragment OrderConProps on OrdersConnection {
  edges {
    node {
      ...orderProps
    }
  }
}

fragment orderProps on Order {
  id
  state
  purpose
  createdAt
  updatedAt
  subOrdersByPool {
    id
  }
}
