query poolsAvailability(
  $ids: [UUID!]
  $startDate: Date
  $endDate: Date
  $includeDates: Boolean!
  $considerAlternativePickupLocations: Boolean
) {
  inventoryPools(ids: $ids) {
    id
    maximumReservationDuration
    reservationAdvanceDays
    transferBufferBeforePickUp
    holidays @include(if: $includeDates) {
      startDate
      endDate
      name
    }
    availability(
      startDate: $startDate
      endDate: $endDate
      considerAlternativePickupLocations: $considerAlternativePickupLocations
    ) @include(if: $includeDates) {
      dates {
        date
        startDateRestrictions
        endDateRestrictions
      }
    }
  }
}
