query poolsAvailability($ids: [UUID!], $startDate: Date, $endDate: Date, $includeAltDates: Boolean!) {
  inventoryPools(ids: $ids) {
    id
    maximumReservationDuration
    reservationAdvanceDays
    transferBufferBeforePickUp
    holidays {
      startDate
      endDate
      name
    }
    availability(startDate: $startDate, endDate: $endDate) {
      dates {
        date
        startDateRestrictions
        endDateRestrictions
      }
      datesForAltLocations @include(if: $includeAltDates) {
        date
        startDateRestrictions
        endDateRestrictions
      }
    }
  }
}
