query getCurrentUser {
  currentUser {
    user {
      id
      firstname
      lastname
      name
    }
    languageToUse {
      id
      localeName
    }
    delegations {
      id
      name
    }
    inventoryPools(orderBy: [{attribute: NAME, direction: ASC}]) {
      id
      name
      maximumReservationTime
      hasReservableItems
    }
    suspensions {
      inventoryPool {
        id
      }
    }
  }
}

