query getCurrentUser($includeDelegation: Boolean, $delegationId: UUID, $includeLanguages: Boolean) {
  currentUser {
    user {
      id
      firstname
      lastname
      name
      delegations {
        id
        name
      }
      inventoryPools(orderBy: [{ attribute: NAME, direction: ASC }]) {
        id
        name
        maximumReservationTime
        hasReservableItems
      }
      suspensions {
        inventoryPool {
          id
        }
      }
      unsubmittedOrder {
        validUntil
        reservations {
          id
          inventoryPool {
            id
            name
          }
          model {
            id
            name
            images {
              id
              imageUrl
            }
            coverImage {
              id
              imageUrl
            }
          }
        }
        invalidReservationIds
        userId
      }
    }
    languageToUse {
      locale
    }
    sessionId
    nav {
      adminUrl
      procureUrl
      manageNavItems {
        name
        url
      }
      documentationUrl
    }
  }
  delegation(id: $delegationId) @include(if: $includeDelegation) {
    id
    name
    inventoryPools(orderBy: [{ attribute: NAME, direction: ASC }]) {
      id
      name
      maximumReservationTime
      hasReservableItems
    }
    suspensions {
      inventoryPool {
        id
      }
    }
  }
  languages @include(if: $includeLanguages) {
    name
    locale
  }
}
