query getCurrentUser {
  currentUser {
    user {
      id
      firstname
      lastname
      name
      delegations {
        id
        name
      }
      inventoryPools(orderBy: [{attribute: NAME, direction: ASC}]) {
        id
        name
        maximumReservationTime
        hasReservableItems
      }
      suspensions {
        inventoryPool {
          id
        }
      }
    }
    languageToUse {
      locale
    }
  }
}
