query getCurrentUserProfilePage {
  currentUser {
    user {
      ...userDataProps

      contracts(orderBy: { attribute: CREATED_AT, direction: DESC }) {
        edges {
          node {
            id
            compactId
            state
            createdAt
            inventoryPool {
              ...poolProps
              isActive
            }
          }
        }
      }

      delegations {
        id
        name
        responsible {
          name
        }
      }

      # NOTE: those are not in the design spec, but should also be listed
      inventoryPools(orderBy: [{ attribute: SHORTNAME, direction: ASC }]) {
        ...poolProps
      }
      suspensions {
        id
        suspendedUntil
        suspendedReason
        inventoryPool {
          ...poolProps
        }
      }
    }
  }
}

fragment userDataProps on User {
  id
  name
  login
  email
  secondaryEmail
  badgeId
  phone
  organization
  orgId
}

fragment poolProps on InventoryPool {
  id
  shortname
  name
}
