query getCurrentUser {
  currentUser {
    user {
      id
      firstname
      lastname
      login
      email
    }
    languageToUse {
      locale
    }
    delegations {
      id
      name
    }
    inventoryPools(orderBy: [{attribute: NAME, direction: ASC}]) {
      id
      name
    }
    suspensions {
      inventoryPool {
        id
      }
    }
    unsubmittedOrder {
      reservations {
        id
        model {
          id
          name
        }
      }
      invalidReservationIds
    }
    draftOrder {
      reservations {
        id
        model {
          id
          name
        }
      }
      invalidReservationIds
    }
  }
}
