query getCurrentUser {
  currentUser {
    user {
      delegations {
        id
        name
        responsible {
          id
          firstname
          lastname
          email
        }
      }
    }
  }
}
