query getCategoryShow(
  $categoryId: UUID!,
  $parentId: UUID,
  $afterCursor: String
) {
  category(id: $categoryId, parentId: $parentId) {
    id
    name
    children {
      id
      name
    }
  }
}
