fragment unsubmittedOrderProps on UnsubmittedOrder {
  validUntil
  reservations {
    endDate
    id
    inventoryPool {
      id
      name
    }
    model {
      id
      name
      images {
        id
        imageUrl
      }
      totalReservableQuantities {
        inventoryPool {
          id
          name
        }
        quantity
      }
    }
    startDate
    status
    user {
      id
    }
  }
  invalidReservationIds
  userId
}