query getDraftOrder($userId: UUID) {
  currentUser(userId: $userId) {
    user {
      draftOrder {
        reservations {
          endDate
          id
          inventoryPool {
            id
            name
          }
          model {
            id
            name
            images {
              id
              imageUrl
            }
          }
          startDate
          status
          user {
            id
          }
          # createdAt
          # updatedAt
        }
        invalidReservationIds
      }
    }
  }
}
