query getShoppingCart($userId: UUID) {
  currentUser(userId: $userId) {
    user {
      unsubmittedOrder {
        validUntil
        reservations {
          endDate
          id
          inventoryPool {
            id
            name
          }
          model {
            id
            name
            images {
              id
              imageUrl
            }
            coverImage {
              id
              imageUrl
            }
          }
          startDate
          status
          user {
            id
          }
          # createdAt
          # updatedAt
        }
        invalidReservationIds
        userId
      }
    }
    settings {
      lendingTermsAcceptanceRequiredForOrder
      lendingTermsUrl
      showContactDetailsOnCustomerOrder
      timeoutMinutes
    }
  }
}
