# NOTE: this must load the same data as getShoppingCart query
# TODO: either use a fragment to ensure that, or refactor to load less data for refresh
mutation {
  refreshTimeout {
    unsubmittedOrder {
      validUntil
      reservations {
        endDate
        id
        inventoryPool {
          id
          name
        }
        model {
          id
          name
          images {
            id
            imageUrl
          }
          totalBorrowableQuantities {
            inventoryPool {
              id
              name
            }
            quantity
          }
        }
        startDate
        status
        user {
          id
        }
        # createdAt
        # updatedAt
      }
      invalidReservationIds
    }
  }
}
