mutation {
  refreshTimeout {
    unsubmittedOrder {
      validUntil
      reservations {
        endDate
        id
        inventoryPool {
          id
          name
        }
        model {
          id
          name
          images {
            id
            imageUrl
          }
        }
        startDate
        status
        user {
          id
        }
        # createdAt
        # updatedAt
      }
      invalidReservationIds
    }
  }
}
