mutation submitOrder(
  $purpose: NonEmptyText!,
  $title: NonEmptyText!,
  $userId: UUID
) {
   submitOrder(
    purpose: $purpose,
    title: $title,
    userId: $userId
  ) {
    id
    title
    purpose
    fromDate
    untilDate
    totalDays
    state: rentalState
    totalQuantity
  }
}
