mutation updateReservations(
  $ids: [UUID!]
  $modelId: UUID!
  $endDate: Date!
  $startDate: Date!
  $quantity: Int!
  $userId: UUID
  $poolIds: [UUID!]
  $pickupLocationId: UUID
) {
  deleteReservationLines(ids: $ids)
  createReservation(
    modelId: $modelId
    endDate: $endDate
    startDate: $startDate
    quantity: $quantity
    userId: $userId
    inventoryPoolIds: $poolIds
    pickupLocationId: $pickupLocationId
    excludeReservationIds: $ids
  ) {
    id
    inventoryPool {
      id
      name
      defaultPickupLocationName
    }
    pickupLocation {
      id
      name
    }
    model {
      id
      name
      transportable
      images {
        id
        imageUrl
      }
      totalReservableQuantities {
        inventoryPool {
          id
          name
        }
        quantity
      }
    }
    startDate
    endDate
    status
    user {
      id
    }
  }
}
