mutation updateReservations(
  $ids: [UUID!]
  $modelId: UUID!
  $endDate: Date!
  $startDate: Date!
  $quantity: Int!
  $userId: UUID
) {
  deleteReservationLines(ids: $ids)
  createReservation(
    modelId: $modelId
    endDate: $endDate
    startDate: $startDate
    quantity: $quantity
    userId: $userId
    excludeReservationIds: $ids
  ) {
    id
    inventoryPool {
      id
      name
    }
    model {
      id
      name
      images {
        id
        imageUrl
      }
    }
    startDate
    endDate
    status
    user {
      id
    }
  }
}
