#!/usr/bin/env bash

SCRIPT_FULL_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname $SCRIPT_FULL_PATH)
ENV_FILE_PATH="$SCRIPT_DIR/../../scripts/_test-env.sh"
source $ENV_FILE_PATH

"$SCRIPT_DIR"/kill-all

tmux send -t leihs-borrow:2.1 "source $ENV_FILE_PATH && boot -C focus" C-m
tmux send -t leihs-borrow:3.1 "source $ENV_FILE_PATH && tail -f log/debug.log" C-m
tmux send -t leihs-borrow:6.1 "source $ENV_FILE_PATH && $SCRIPT_DIR/../../scripts/start-legacy-mock-server" C-m
