query getModelBookingCalendar(
  $modelId: UUID!
  $startDate: Date
  $endDate: Date
  $userId: UUID
) # $pools: [UUID!]!
{
  model(id: $modelId) {
    id
    name
    manufacturer

    # availableQuantityInDateRange(startDate: $startDate, endDate: $endDate, userId: $userId)

    availability(
      startDate: $startDate
      endDate: $endDate
      userId: $userId
    ) # inventoryPoolIds: $pools
    {
      inventoryPool {
        id
        name
      }
      dates {
        date
        quantity
        startDateRestrictions
        endDateRestrictions
      }
    }
  }
}
