mutation createReservationForModel(
  $modelId: UUID!
  $endDate: Date!
  $startDate: Date!
  $quantity: Int!
  $userId: UUID
) {
  createReservation(
    modelId: $modelId
    endDate: $endDate
    startDate: $startDate
    quantity: $quantity
    userId: $userId
  ) {
    id
  }
}
