mutation createReservationForModel(
  $modelId: UUID!
  $endDate: Date!
  $startDate: Date!
  $quantity: Int!
  $userId: UUID
  $poolIds: [UUID!]
  $pickupLocationId: UUID
) {
  createReservation(
    modelId: $modelId
    endDate: $endDate
    startDate: $startDate
    quantity: $quantity
    userId: $userId
    inventoryPoolIds: $poolIds
    pickupLocationId: $pickupLocationId
  ) {
    id
  }
}
