query getAvailability(
  $modelId: UUID!
  $startDate: Date
  $endDate: Date
  $userId: UUID
  $poolIds: [UUID!]
  $excludeReservationIds: [UUID!]
) {
  model(userId: $userId, id: $modelId) {
    availability(
      startDate: $startDate
      endDate: $endDate
      inventoryPoolIds: $poolIds
      excludeReservationIds: $excludeReservationIds
    ) {
      inventoryPool {
        id
        name
        maximumReservationDuration
        reservationAdvanceDays
        transferBufferBeforePickUp
        defaultPickupLocationName
        pickupLocations {
          id
          name
          description
        }
        holidays {
          startDate
          endDate
          name
        }
      }
      dates {
        date
        quantity
        startDateRestrictions
        endDateRestrictions
      }
      datesForAltLocations {
        date
        quantity
        startDateRestrictions
        endDateRestrictions
      }
    }
  }
}
