query getModelShow(
  $modelId: UUID!, 
  $startDate: Date, 
  $endDate: Date, 
  $userId: UUID,
  $bothDatesGiven: Boolean!
  $pools: [UUID!]
) {
  model(id: $modelId) {
    id
    name
    manufacturer
    description
    # availableQuantityInDateRange(startDate: $startDate, endDate: $endDate, userId: $userId) 
    #   @include(if: $bothDatesGiven)
    isFavorited
    images {
      id
      imageUrl
    }
    coverImage {
      id
      imageUrl
    }
    attachments {
      id
      filename
      url
      size
      # content_type # FIXME: include this field when API bug is fixed
    }
    properties {
      id
      key
      value
    }
    recommends(first: 12) {
      edges {
        node {
          id
          name
          manufacturer
          images {
            id
            imageUrl
          }
        }
      }
    }

    # FIXME: put in separate query
    availability(
      startDate: $startDate
      endDate: $endDate
      inventoryPoolIds: $pools
    ) @include(if: $bothDatesGiven) {
      inventoryPool {
        id
        name
      }
      dates {
        date
        quantity
        startDateRestriction
        endDateRestriction
      }
    }
  }
}
