# query ModelCalendarData(
#   $models: [UUID!]!
#   $pools: [UUID!]!
#   $startDate: Date!
#   $endDate: Date!
# ) {
#   models(ids: $models) {
#     edges {
#       node {
#         id
#         name
#         availability(
#           startDate: $startDate
#           endDate: $endDate
#           inventoryPoolIds: $pools
#         ) {
#           inventoryPool {
#             id
#             name
#           }
#           dates {
#             date
#             quantity
#             startDateRestriction
#             endDateRestriction
#           }
#         }
#       }
#     }
#   }
# }
