mutation setModelFavorite($modelId: UUID!, $isFav: Boolean!, $userId: UUID) {
  favoriteModel(id: $modelId, userId: $userId) @include(if: $isFav) {
    id
  }
  unfavoriteModel(id: $modelId, userId: $userId) @skip(if: $isFav) {
    id
  }
}
