query getRootCategories(
  $count: Int,
  $userId: UUID,
  $poolIds: [UUID!]
) {
  categories: rootCategories(limit: $count, userId: $userId, poolIds: $poolIds) {
    id
    name
    images {
      imageUrl
    }
  }
}
