#!/bin/sh

# fetch schema from server and compare against the checked-in version

# NOTE: ensure the bin is installed (comes from npm package)
npm run -s graphql-schema-diff -- --version &> /dev/null || npm install --silent --no-audit

RES=1

mv schema.graphql schema_orig.graphql
./scripts/dump-graphql-schema

npm run -s graphql-schema-diff -- \
  --fail-on-any-changes schema_orig.graphql schema.graphql \
  && RES=0 || RES=1

mv schema_orig.graphql schema.graphql
exit $RES
