#!/bin/bash

export DATABASE_URL="postgresql://localhost:5432/leihs_next?max-pool-size=5"

# prepare:
# TODO: detect if this is needed and only run then
# ./scripts/prepare-shared-ui.sh || exit 1

# run stuff in parallel:
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
pids=( )

# jobs
( ./scripts/start-legacy-dev       ) & pids+=( $! )
( ./scripts/start-backend-dev      ) & pids+=( $! )
( ./scripts/start-frontend-dev     ) & pids+=( $! )
( cd leihs-ui && npm run watch:lib ) & pids+=( $! )

# abort all if a job fails
for pid in "${pids[@]}"; do wait "$pid" || exit 1; done