#!/bin/bash

export PORT=3250 # NOTE: this var is not used everywhere but has same hardcoded value… so just dont change it ;)
export DATABASE_URL="${DATABASE_URL:-"postgresql://localhost:5432/leihs?max-pool-size=5"}"
# DEV_BROWSER="${DEV_BROWSER:-"org.mozilla.firefoxdeveloperedition"}" # "com.google.Chrome.canary" | "com.google.Chrome"

# prepare:
# - set DB (also makes sure it is setup before wasting time compiling)
psql $(echo "$DATABASE_URL" | sed 's/?.*$//') -AXtq1c "UPDATE settings SET external_base_url='http://localhost:${PORT}' WHERE id=0;"
printf "DB settings: "
psql $(echo "$DATABASE_URL" | sed 's/?.*$//') -AXtqc "SELECT array_to_json(array_agg(row_to_json(settings, TRUE)), TRUE) FROM settings WHERE id=0;"
echo; echo; echo

# - UI: get cached build artefact or build it locally otherwise
./leihs-ui/bin/build || ./scripts/prepare-shared-ui.sh || exit 1

# run stuff in parallel:
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
pids=( )

# jobs
( ./scripts/start-legacy-dev       ) & pids+=( $! )
( ./scripts/start-backend-dev      ) & pids+=( $! )
( ./scripts/start-frontend-dev     ) & pids+=( $! )
( cd leihs-ui && npm run watch:lib ) & pids+=( $! )


# # on mac, open brower tabs
# if $(type open &> /dev/null ); then
#   open -b "$DEV_BROWSER" "http://localhost:${PORT}"
#   open -b "$DEV_BROWSER" "http://localhost:3210" # legacy, for login
# fi

# abort all if a job fails
for pid in "${pids[@]}"; do wait "$pid" || exit 1; done