#!/bin/bash

# NOTE: we need  legacy webapp to fetch availabilty data from old API!

source ./scripts/_test-env.sh

cd ../legacy || {
    echo "ERROR: could not find `leihs/legacy`. Run this from inside superproject (`leihs/borrow`)!"
    exit 1
}

export RAILS_LOG_LEVEL=debug
bundle exec rails s -p $LEIHS_LEGACY_PORT -b 127.0.0.1