#!/bin/sh

. ./scripts/_dev-env.sh

# git submodule update --init --recursive
export LEIHS_LEGACY_HTTP_BASE_URL="http://localhost:3210"

# try with the local cache, if it doesnt work then download from the network
bin/boot --offline focus \
  || bin/boot focus
