query {
  pickups {
    date
    quantity
    inventoryPool {
      id
      name
    }
    reservations {
      model {
        name
      }
      poolOrder {
        order {
          id
          purpose
        }
      }
    }
    isApproved
  }
}
