query {
  returns {
    date
    quantity
    inventoryPool {
      id
      name
    }
    reservations {
      id
      item {
        inventoryCode
        model {
          name
        }
      }
      option {
        inventoryCode
        name
      }
      poolOrder {
        order {
          id
          purpose
        }
      }
    }
  }
}
