mutation addModelToOrder(
  $modelId: UUID!
  $quantity: Int!
  $inventoryPoolId: UUID!
  $startDate: Date!
  $endDate: Date!
) {
  reservation: createReservation(
    modelId: $modelId
    startDate: $startDate
    endDate: $endDate
    inventoryPoolId: $inventoryPoolId
    quantity: $quantity
  ) {
    id
  }
}
