query allMyOrders {
  orders {
    id
    purpose
    state
    subOrdersByPool {
      id
      state
      rejectedReason
      inventoryPool {
        id
      }
      reservations {
        id
        startDate
        endDate
        model {
          id
        }
        status
      }
    }
  }
}
