mutation createReservationForModel(
  $modelId: UUID!
  $endDate: Date!
  $startDate: Date!
  $quantity: Int!
) {
  createReservation(
    modelId: $modelId
    endDate: $endDate
    startDate: $startDate
    quantity: $quantity
  ) {
    id
  }
}
