query getFavoriteModels(
  $afterCursor: String
) {
  models(
    first: 20,
    after: $afterCursor,
    isFavorited: true
  ) {
    edges {
      node {
        ...modelListProps
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

fragment modelListProps on Model {
  id
  name
  description
  manufacturer
  images {
    id
    imageUrl
    # thumbnails { id size imageUrl }
  }
}
