query getModelShow($modelId: UUID!, $withOrderForm: Boolean!, $startDate: Date!, $endDate: Date!) {
  model(id: $modelId) {
    id
    name
    manufacturer
    description
    images {
      id
      imageUrl
    }
    attachments {
      id
      filename
      url
      size
      # content_type # FIXME: include this field when API bug is fixed
    }
    properties {
      id
      key
      value
    }

    availableQuantityInDateRange(startDate: $startDate, endDate: $endDate) @include(if: $withOrderForm)

    recommends(first: 12) {
      edges {
        node {
          id
          name
          manufacturer
          images {
            id
            imageUrl
          }
        }
      }
    }
  }
}
