query searchModels($searchTerm: String, $startDate: Date!, $endDate: Date!) {
  models(searchTerm: $searchTerm, first: 12) {
    edges {
      node {
        ...modelListProps
      }
    }
  }
}

fragment modelListProps on Model {
  id
  name
  description
  manufacturer
  images {
    id
    imageUrl
    # thumbnails { id size imageUrl }
  }
  availableQuantityInDateRange(startDate: $startDate, endDate: $endDate)
}
