query searchModels(
  $searchTerm: String
  $startDate: String!
  $endDate: String!
  $categories: [UUID!]
  $pools: [UUID!]
) {
  models(
    searchTerm: $searchTerm
    startDate: $startDate
    endDate: $endDate
    categoryIds: $categories
    first: 100
  ) {
    edges {
      node {
        ...modelListProps
      }
    }
  }
}

fragment modelListProps on Model {
  id
  name
  description
  manufacturer
  images {
    id
    imageUrl
    # thumbnails {
    #   id
    #   size
    #   imageUrl
    # }
  }
  availableQuantityInDateRange
}

