mutation applyTemplate(
  $id: UUID
  $endDate: Date!
  $startDate: Date!
  $userId: UUID
) {
  applyTemplate(
    userId: $userId
    id: $id
    startDate: $startDate
    endDate: $endDate
  ) {
    id
  }

  refreshTimeout(userId: $userId) {
    unsubmittedOrder {
      validUntil
      reservations {
        endDate
        id
        inventoryPool {
          id
          name
        }
        model {
          id
          name
          images {
            id
            imageUrl
          }
        }
        startDate
        status
        user {
          id
        }
      }
      invalidReservationIds
      userId
    }
  }
}
