query templateShow($id: UUID!, $userId: UUID) {
  template(id: $id, userId: $userId) {
    id
    name
    inventoryPool {
      id
      name
    }
    lines {
      model {
        id
        name
        manufacturer
        isReservable
        images {
          id
          imageUrl
        }
        coverImage {
          id
          imageUrl
        }
        isFavorited
      }
      quantity
    }
  }
}
