query templateShow(
  $id: UUID!
  $userId: UUID
  $startDate: Date
  $endDate: Date
) {
  template(id: $id, userId: $userId) {
    id
    name
    inventoryPool {
      id
      name
      maximumReservationDuration
      reservationAdvanceDays
      holidays {
        startDate
        endDate
        name
      }
      availability(startDate: $startDate, endDate: $endDate) {
        dates {
          date
          startDateRestrictions
          endDateRestrictions
        }
      }
    }
    lines {
      model {
        id
        name
        manufacturer
        isReservable
        images {
          id
          imageUrl
        }
        coverImage {
          id
          imageUrl
        }
        isFavorited
      }
      quantity
    }
  }
}
