query getModelAvailableQuantity(
  $modelId: UUID!
  $startDate: Date!
  $endDate: Date!
) {
  model(id: $modelId) {
    availableQuantityInDateRange(
      startDate: $startDate, endDate: $endDate)
  }
}
