context:
  task_defaults:
    git_options:
      submodules:
        include_match: ^.*$
  tasks:
    database-submodule-consistency:
      name: "database and spec/support/legacy-api/database point to the same commit"
      scripts:
        main:
          body: |
            #!/usr/bin/env bash
            set -euo pipefail

            DB_LEGACY_ID=$(git -C spec/support/legacy-api/database log --format="%H" -n 1)
            DB_TOP_ID=$(git -C database log --format="%H" -n 1)
            echo "database | toplevel: ${DB_LEGACY_ID}"
            echo "database | legacy:   ${DB_TOP_ID}"

            test $DB_TOP_ID == $DB_LEGACY_ID
